# Makefile for emulator framework

SRCS= emu.cc input.cc io.cc machine.cc ram.cc rom.cc video.cc
OBJS= emu.o input.o io.o machine.o ram.o rom.o video.o
LIBRARY= emu
CHECK_OBJS= emu_test.o debug_test.o

include ../Makefile.inc
