# Galaga Driver

SRCS= namco51.cc namco06.cc galaga.cc
OBJS= namco51.o namco06.o galaga.o
LIBRARY= galaga

LIBS+= -lemu -lcpu

CHECK_OBJS= galaga_test.o
CPPFLAGS+= -I../cpu


include ../Makefile.inc

